name: "pre-release"

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-release:
    name: "Release Builder"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'

      - name: "Build .jar"
        run: |
          chmod +x gradlew
          ./gradlew desktop:dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{github.run_id + github.run_number}}
          title: "Release ${{github.run_id + github.run_number}}"
          files: *.jar
